/*************************************************************************
 * Copyright (C) 2015 Mugurtham Technology, Incorporated 
 * All Rights Reserved.
 * 
 * NOTICE:  All the intellectual and technical concepts contained
 * herein are proprietary to Mugurtham Technology, Incorporated
 * and may be covered by Indian and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Mugurtham Technology, Incorporated.
/*************************************************************************
/*
==========================================================================================
THIS CONSTANT IS A DATASTORE FOR PROCESSING ASTROLOGICAL MATCHERS
==========================================================================================
*/

var app = angular.module('MugurthamApp');

app.constant('ConstantMatchingStarsForGroom', {

    Aswini:[  
      {  
          ID:"1",
          Star:'Bharani',
          Match:'8',
          Category:'Uthamam',
          Accepted:'True'
      },
      {  
          ID:"2",
          Star:'Karthigai',
          Match:'8',
          Category:'Uthamam',
          Accepted:'True'
      },
      {  
          ID:"3",
          Star:'Rohini',
          Match:'7',
          Category:'Uthamam',
          Accepted:'True'
      },
      {  
          ID:"4",
          Star:'Mrigasheersham',
          Match:'8',
          Category:'Uthamam',
          Accepted:'True'
      },
      {  
          ID:"5",
          Star:'Thiruvaathirai',
          Match:'7',
          Category:'Uthamam',
          Accepted:'True'
      },
      {  
          ID:"6",
          Star:'Punarpoosam',
          Match:'9',
          Category:'Uthamam',
          Accepted:'True'
      },
      {  
          ID:"7",
          Star:'Poosam',
          Match:'7',
          Category:'Uthamam',
          Accepted:'True'
      },
      {  
          ID:"8",
          Star:'Pooram',
          Match:'8',
          Category:'Uthamam',
          Accepted:'True'
      },
      {  
          ID:"9",
          Star:'Uthiram',
          Match:'8',
          Category:'Uthamam',
          Accepted:'True'
      },
      {  
          ID:"10",
          Star:'Anusham',
          Match:'6',
          Category:'Uthamam',
          Accepted:'True'
      },
      {  
          ID:"11",
          Star:'Pooraadam',
          Match:'7',
          Category:'Uthamam',
          Accepted:'True'
      },
      {  
          ID:"12",
          Star:'Uthiraadam',
          Match:'7',
          Category:'Uthamam',
          Accepted:'True'
      },
      {  
          ID:"13",
          Star:'Thiruvonam',
          Match:'6',
          Category:'Uthamam',
          Accepted:'True'
      },
      {  
          ID:"14",
          Star:'Chithirai',
          Match:'6',
          Category:'Mathimam',
          Accepted:'True'
      },
      {  
          ID:"15",
          Star:'Visaakam',
          Match:'8',
          Category:'Mathimam',
          Accepted:'True'
      },
      {  
          ID:"16",
          Star:'Sadayam',
          Match:'5',
          Category:'Mathimam',
          Accepted:'True'
      },
      {  
          ID:"17",
          Star:'Poorattathi',
          Match:'6',
          Category:'Mathimam',
          Accepted:'True'
      },
      {  
          ID:"18",
          Star:'Uthirattathi',
          Match:'5',
          Category:'Mathimam',
          Accepted:'True'
      },
      {  
          ID:"19",
          Star:'Avittam',
          Match:'6',
          Category:'Mathimam',
          Accepted:'True'
      }
    ],
    Bharani:[  
       {  
           ID:"1",
           Star:'Aswini',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Rohini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Mrigasheersham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Thiruvaathirai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Punarpoosam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Uthiram',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Hastham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Swaathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Uthiraadam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Thiruvonam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Karthigai',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Aayilyam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Makam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Kettai',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Moolam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Revathi',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Chithirai',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Visakkam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Sadayam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Karthigai:[  
       {  
           ID:"1",
           Star:'Aswini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Bharani',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Rohini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Mrigasheersham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Thiruvaathirai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Poosam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Aayilyam',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Makam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Pooram',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Hastham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Swaathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Anusham',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Kettai',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Moolam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Revathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Karthigai',
           Match:'0',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Chithirai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Sadayam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Uthirattathi',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Avittam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Rohini:[  
       {  
           ID:"1",
           Star:'Aswini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Rohini',
           Match:'0',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Mrigasheersham',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Punarpoosam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Poosam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Uthiram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Anusham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Poorattathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Bharani',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Karthigai',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Aayilyam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Makam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Chithirai',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Visaakam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Kettai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Moolam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Pooraadam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Avittam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Uthirattathi',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Revathi',
           Match:'4',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"21",
           Star:'Pooram',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Mrigasheersham:[  
       {  
           ID:"1",
           Star:'Bharani',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Rohini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Thiruvaathirai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Punarpoosam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Poosam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Aayilyam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Uthiram',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Hastham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Swaathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Visaakam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Anusham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Kettai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Pooraadam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Thiruvonam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Sadayam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Poorattathi',
           Match:'5',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Aswini',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Karthigai',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Mrigasheersham',
           Match:'0',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Moolam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"21",
           Star:'Uthirattathi',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"22",
           Star:'Revathi',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"23",
           Star:'Makam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"24",
           Star:'Pooram',
           Match:'8',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Thiruvaathirai:[  
       {  
           ID:"1",
           Star:'Mrigasheersham',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Thiruvaathirai',
           Match:'0',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Poosam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Pooram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Uthiram',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Pooraadam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Uthiraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Poorattathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Uthirattathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Karthigai',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Punarpoosam',
           Match:'8',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Makam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Chithirai',
           Match:'8',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Visaakam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Moolam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Avittam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Revathi',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Aswini',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Bharani',
           Match:'4',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Punarpoosam:[  
       {  
           ID:"1",
           Star:'Rohini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Thiruvaathirai',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Poosam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Aayilyam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Hastham',
           Match:'10',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Chithirai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Swaathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Anusham',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Kettai',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Pooraadam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Thiruvonam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Avittam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Sadayam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Uthirattathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Revathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Aswini',
           Match:'5',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Bharani',
           Match:'5',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Mrigasheersham',
           Match:'5',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Punarpoosam',
           Match:'0',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Moolam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       }
    ],
    Poosam:[  
       {  
           ID:"1",
           Star:'Aswini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Karthigai',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Mrigasheersham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Aayilyam',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Makam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Uthiram',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Hastham',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Swaathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Kettai',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Moolam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Uthiraadam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Revathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Rohini',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Punarpoosam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Poosam',
           Match:'0',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Chithirai',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Visaakam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Avittam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Sadayam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Thiruvaathirai',
           Match:'4',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"21",
           Star:'Poorattathi',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Aayilyam:[  
       {  
           ID:"1",
           Star:'Bharani',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Karthigai',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Rohini',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Poosam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Uthiram',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Hastham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Chithirai',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Swaathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Visaakam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Anusham',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Pooraadam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Uthiraadam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Thiruvonam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Avittam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Sadayam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Poorattathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Uthirattathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Mrigasheersham',
           Match:'4',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Thiruvaathirai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Punarpoosam',
           Match:'4',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Makam:[  
       {  
           ID:"1",
           Star:'Bharani',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Karthigai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Makam',
           Match:'0',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Pooram',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Uthiram',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Hastham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Chithirai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Swaathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Visaakam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Anusham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Pooraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Uthiraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Thiruvonam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Avittam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Sadayam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Poorattathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Uthirattathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Thiruvaathirai',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Poosam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Rohini',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"21",
           Star:'Mrigasheersham',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Pooram:[  
       {  
           ID:"1",
           Star:'Aswini',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Thiruvaathirai',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Uthiram',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Hastham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Swaathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Uthiraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Thiruvonam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Poorattathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Revathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Karthigai',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Makam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Pooram',
           Match:'0',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Chithirai',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Kettai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Moolam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Sadayam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Mrigasheersham',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Visaakam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Avittam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Uthiram:[  
       {  
           ID:"1",
           Star:'Aswini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Bharani',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Rohini',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Mrigasheersham',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Thiruvaathirai',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Pooram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Hastham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Swaathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Anusham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Kettai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Pooraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Thiruvonam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Uthirattathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Revathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Poosam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Aayilyam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Makam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Uthiram',
           Match:'0',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Moolam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Sadayam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"21",
           Star:'Avittam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Hastham:[  
       {  
           ID:"1",
           Star:'Karthigai',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Mrigasheersham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Punarpoosam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Poosam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Makam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Uthiram',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Hastham',
           Match:'0',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Anusham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Kettai',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Moolam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Pooraadam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Uthiraadam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Uthirattathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Revathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Bharani',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Aayilyam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Pooram',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Chithirai',
           Match:'8',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Avittam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Poorattathi',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"21",
           Star:'Visaakam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Chithirai:[  
       {  
           ID:"1",
           Star:'Rohini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Thiruvaathirai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Punarpoosam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Aayilyam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Pooram',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Visaakam',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Anusham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Moolam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Pooraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Thiruvonam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Poorattathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Bharani',
           Match:'8',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Makam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Hastham',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Swaathi',
           Match:'8',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Uthiraadam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Sadayam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Revathi',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Aswini',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Karthigai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"21",
           Star:'Poosam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"22",
           Star:'Kettai',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Swaathi:[  
       {  
           ID:"1",
           Star:'Bharani',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Karthigai',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Mrigasheersham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Punarpoosam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Poosam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Aayilyam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Makam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Uthiram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Anusham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Kettai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Moolam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Pooraadam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Uthiraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Uthirattathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Revathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Pooram',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Visaakam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Avittam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Chithirai',
           Match:'8',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Poorattathi',
           Match:'8',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Visaakam:[  
       {  
           ID:"1",
           Star:'Rohini',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Mrigasheersham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Thiruvaathirai',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Aayilyam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Makam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Pooram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Visaakam',
           Match:'0',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Moolam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Pooraadam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Thiruvonam',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Avittam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Aswini',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Bharani',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Poosam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Hastham',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Chithirai',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Swaathi',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Anusham',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Kettai',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Sadayam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"21",
           Star:'Revathi',
           Match:'8',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Anusham:[  
       {  
           ID:"1",
           Star:'Aswini',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Karthigai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Rohini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Mrigasheersham',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Punarpoosam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Aayilyam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Makam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Uthiram',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Kettai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Uthiraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Thiruvonam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Sadayam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Revathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Hastham',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Chithirai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Anusham',
           Match:'0',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Avittam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Poorattathi',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Swaathi',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Visaakam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Kettai:[  
       {  
           ID:"1",
           Star:'Bharani',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Karthigai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Rohini',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Mrigasheersham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Punarpoosam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Poosam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Pooram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Uthiram',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Hastham',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Swaathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Anusham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Pooraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Uthiraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Thiruvonam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Sadayam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Uthirattathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Chithirai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Visaakam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Avittam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Poorattathi',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Moolam:[  
       {  
           ID:"1",
           Star:'Bharani',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Karthigai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Rohini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Mrigasheersham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Thiruvaathirai',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Poosam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Pooram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Uthiram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Hastham',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Visaakam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Pooraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Uthiraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Thiruvonam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Avittam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Sadayam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Poorattathi',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Uthirattathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Punarpoosam',
           Match:'8',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Chithirai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Swaathi',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Pooraadam:[  
       {  
           ID:"1",
           Star:'Aswini',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Rohini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Mrigasheersham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Thiruvaathirai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Punarpoosam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Uthiram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Hastham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Uthiraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Thiruvonam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Poorattathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Revathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Aayilyam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Makam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Swaathi',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Moolam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Pooraadam',
           Match:'0',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Avittam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Sadayam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Chithirai',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Visaakam',
           Match:'4',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"21",
           Star:'Kettai',
           Match:'4',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Uthiraadam:[  
       {  
           ID:"1",
           Star:'Aswini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Bharani',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Thiruvaathirai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Poosam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Pooram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Hastham',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Swaathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Pooraadam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Thiruvonam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Uthirattathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Revathi',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Aayilyam',
           Match:'8',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Makam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Anusham',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Kettai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Uthiraadam',
           Match:'0',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Sadayam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Chithirai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Moolam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Avittam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Thiruvonam:[  
       {  
           ID:"1",
           Star:'Aswini',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Bharani',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Mrigasheersham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Punarpoosam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Aayilyam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Makam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Uthiram',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Chithirai',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Visaakam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Anusham',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Moolam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Uthiraadam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Thiruvonam',
           Match:'0',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Avittam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Poorattathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Uthirattathi',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Revathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Pooram',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Kettai',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Pooraadam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Avittam:[  
       {  
           ID:"1",
           Star:'Rohini',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Thiruvaathirai',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Punarpoosam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Poosam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Aayilyam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Pooram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Visaakam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Pooraadam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Thiruvonam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Poorattathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Aswini',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Karthigai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Makam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Hastham',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Swaathi',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Moolam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Sadayam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Uthirattathi',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Uthiram',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Anusham',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"21",
           Star:'Uthiraadam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Sadayam:[  
       {  
           ID:"1",
           Star:'Aswini',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Bharani',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Karthigai',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Mrigasheersham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Punarpoosam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Poosam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Aayilyam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Makam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Pooram',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Uthiram',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Anusham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Kettai',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Moolam',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Uthiraadam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Uthirattathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Revathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Chithirai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Visaakam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Pooraadam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Poorattathi',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"21",
           Star:'Avittam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Poorattathi:[  
       {  
           ID:"1",
           Star:'Rohini',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Mrigasheersham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Thiruvaathirai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Pooram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Thiruvonam',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Aswini',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Poosam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Aayilyam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Makam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Hastham',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Swaathi',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Anusham',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Kettai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Moolam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Chithirai',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Pooraadam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Avittam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Sadayam',
           Match:'5',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Uthirattathi',
           Match:'8',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Uthirattathi:[  
       {  
           ID:"1",
           Star:'Aswini',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Rohini',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Mrigasheersham',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Thiruvaathirai',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Punarpoosam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Uthiram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Hastham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Swaathi',
           Match:'6',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Uthiraadam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Thiruvonam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Uthirattathi',
           Match:'0',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Revathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Karthigai',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Aayilyam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Makam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Kettai',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Moolam',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Avittam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Sadayam',
           Match:'4',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Poorattathi',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       }
    ],
    Revathi:[  
       {  
           ID:"1",
           Star:'Bharani',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"2",
           Star:'Karthigai',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"3",
           Star:'Rohini',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"4",
           Star:'Mrigasheersham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"5",
           Star:'Thiruvaathirai',
           Match:'9',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"6",
           Star:'Punarpoosam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"7",
           Star:'Poosam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"8",
           Star:'Pooram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"9",
           Star:'Uthiram',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"10",
           Star:'Hastham',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"11",
           Star:'Swaathi',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"12",
           Star:'Anusham',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"13",
           Star:'Pooraadam',
           Match:'8',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"14",
           Star:'Uthiraadam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"15",
           Star:'Thiruvonam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"16",
           Star:'Sadayam',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"17",
           Star:'Uthirattathi',
           Match:'7',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"18",
           Star:'Revathi',
           Match:'0',
           Category:'Uthamam',
           Accepted:'True'
       },
       {  
           ID:"19",
           Star:'Chithirai',
           Match:'7',
           Category:'Mathimam',
           Accepted:'True'
       },
       {  
           ID:"20",
           Star:'Visaakam',
           Match:'6',
           Category:'Mathimam',
           Accepted:'True'
       }
    ]
});


